/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcolatrice;

/**
 *
 * @author andrew
 */
public class Frame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frame.class.getName());

    private float memory;

    public float getMemory() {
        return memory;
    }

    public void setMemory(float memory) {
        this.memory = memory;
    }

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        currentTextLabel = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonDot = new javax.swing.JButton();
        buttonResult = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        buttonClear = new javax.swing.JButton();
        buttonMemory = new javax.swing.JButton();
        buttonStore = new javax.swing.JButton();
        buttonMemoryPlus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buttonSin = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        buttonSec = new javax.swing.JButton();
        buttonPower = new javax.swing.JButton();
        buttonRootOfN = new javax.swing.JButton();
        buttonFactorial = new javax.swing.JButton();
        buttonInvert = new javax.swing.JButton();
        buttonSpace = new javax.swing.JButton();
        buttonSquareRoot = new javax.swing.JButton();
        memoryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comfortaa", 1, 24)); // NOI18N
        jLabel1.setText("Calcolatrice");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(176, 6, 156, 28);
        getContentPane().add(currentTextLabel);
        currentTextLabel.setBounds(22, 40, 355, 21);

        button1.setLabel("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(18, 80, 51, 41);

        button2.setText("2");
        button2.setPreferredSize(new java.awt.Dimension(22, 22));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(80, 80, 51, 41);

        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3);
        button3.setBounds(140, 80, 51, 41);

        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4);
        button4.setBounds(18, 130, 51, 41);

        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5);
        button5.setBounds(80, 130, 51, 41);

        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6);
        button6.setBounds(140, 130, 51, 41);

        button7.setLabel("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7);
        button7.setBounds(18, 180, 51, 41);

        button8.setLabel("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8);
        button8.setBounds(80, 180, 50, 41);

        button9.setLabel("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9);
        button9.setBounds(140, 180, 51, 41);

        button0.setText("0");
        button0.setPreferredSize(new java.awt.Dimension(22, 22));
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        getContentPane().add(button0);
        button0.setBounds(18, 230, 51, 41);

        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPlus);
        buttonPlus.setBounds(200, 80, 51, 41);

        buttonMinus.setText("-");
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMinus);
        buttonMinus.setBounds(200, 130, 51, 41);

        buttonMultiply.setText("X");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMultiply);
        buttonMultiply.setBounds(200, 180, 51, 41);

        buttonDivide.setText("/");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDivide);
        buttonDivide.setBounds(200, 230, 51, 41);

        buttonDot.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        buttonDot.setText(".");
        buttonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDotActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDot);
        buttonDot.setBounds(80, 230, 51, 41);

        buttonResult.setText("=");
        buttonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResultActionPerformed(evt);
            }
        });
        getContentPane().add(buttonResult);
        buttonResult.setBounds(140, 230, 51, 41);

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText(" ");
        getContentPane().add(errorLabel);
        errorLabel.setBounds(31, 330, 370, 20);

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        getContentPane().add(buttonClear);
        buttonClear.setBounds(20, 280, 70, 41);

        buttonMemory.setText("Mem");
        buttonMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMemory);
        buttonMemory.setBounds(450, 280, 80, 41);

        buttonStore.setText("Store");
        buttonStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStoreActionPerformed(evt);
            }
        });
        getContentPane().add(buttonStore);
        buttonStore.setBounds(270, 280, 80, 41);

        buttonMemoryPlus.setText("M+");
        buttonMemoryPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryPlusActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMemoryPlus);
        buttonMemoryPlus.setBounds(360, 280, 80, 41);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(22, 19, 0, 0);

        buttonSin.setText("Sin");
        buttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSin);
        buttonSin.setBounds(470, 70, 60, 41);

        buttonCos.setText("Cos");
        buttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCos);
        buttonCos.setBounds(470, 120, 60, 41);

        buttonTan.setText("Tan");
        buttonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTanActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTan);
        buttonTan.setBounds(470, 220, 60, 41);

        buttonSec.setText("Sec");
        buttonSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSecActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSec);
        buttonSec.setBounds(470, 170, 60, 41);

        buttonPower.setText("^");
        buttonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPowerActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPower);
        buttonPower.setBounds(340, 80, 51, 41);

        buttonRootOfN.setText("√");
        buttonRootOfN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRootOfNActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRootOfN);
        buttonRootOfN.setBounds(260, 80, 60, 41);

        buttonFactorial.setText("n!");
        buttonFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFactorialActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFactorial);
        buttonFactorial.setBounds(340, 130, 51, 41);

        buttonInvert.setText("1/n");
        buttonInvert.setMaximumSize(new java.awt.Dimension(72, 24));
        buttonInvert.setMinimumSize(new java.awt.Dimension(72, 24));
        buttonInvert.setPreferredSize(new java.awt.Dimension(72, 24));
        buttonInvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvertActionPerformed(evt);
            }
        });
        getContentPane().add(buttonInvert);
        buttonInvert.setBounds(400, 130, 60, 41);

        buttonSpace.setText("Space");
        buttonSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpaceActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSpace);
        buttonSpace.setBounds(140, 280, 100, 41);

        buttonSquareRoot.setText("2√");
        buttonSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSquareRootActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSquareRoot);
        buttonSquareRoot.setBounds(400, 80, 60, 41);

        memoryLabel.setText("No mem");
        getContentPane().add(memoryLabel);
        memoryLabel.setBounds(20, 20, 60, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTextToLabel(String text) {
        currentTextLabel.setText(currentTextLabel.getText() + text);
        System.out.println(currentTextLabel.getText() + text);
    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        addTextToLabel("1");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        addTextToLabel("2");
    }//GEN-LAST:event_button2ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        addTextToLabel("5");
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        addTextToLabel("6");
    }//GEN-LAST:event_button6ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        addTextToLabel("3");
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        addTextToLabel("4");
    }//GEN-LAST:event_button4ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        addTextToLabel("7");
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        addTextToLabel("8");
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        addTextToLabel("9");
    }//GEN-LAST:event_button9ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        addTextToLabel("0");
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDotActionPerformed
        addTextToLabel(".");
    }//GEN-LAST:event_buttonDotActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        currentTextLabel.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResultActionPerformed

        try {
            MathExpressionParser expressionParser
                    = new MathExpressionParser();

            double calculatedResult = expressionParser
                    .parseAndEvaluateMathematicalExpression(currentTextLabel.getText());
            System.out.printf("%-25s = %.6f%n", currentTextLabel.getText(), calculatedResult);

            System.out.printf("\nResult: " + currentTextLabel.getText());

            currentTextLabel.setText(String.valueOf(calculatedResult));

        } catch (Exception e) {
            errorLabel.setText(e.getMessage());
            System.out.printf("%-25s => ERROR: %s%n",
                    currentTextLabel.getText(),
                    e.getMessage());

        }
    }//GEN-LAST:event_buttonResultActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        addTextToLabel(" + ");
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        addTextToLabel(" - ");
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        addTextToLabel(" * ");
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        addTextToLabel(" / ");
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void buttonSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpaceActionPerformed
        addTextToLabel(" ");
    }//GEN-LAST:event_buttonSpaceActionPerformed

    private void buttonRootOfNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRootOfNActionPerformed
        addTextToLabel("root ");
    }//GEN-LAST:event_buttonRootOfNActionPerformed

    private void buttonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPowerActionPerformed
        addTextToLabel(" ^ ");
    }//GEN-LAST:event_buttonPowerActionPerformed

    private void buttonSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSquareRootActionPerformed
        addTextToLabel("root 2");
    }//GEN-LAST:event_buttonSquareRootActionPerformed

    private void buttonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinActionPerformed
        addTextToLabel("sin ");
    }//GEN-LAST:event_buttonSinActionPerformed

    private void buttonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCosActionPerformed
        addTextToLabel("cos ");
    }//GEN-LAST:event_buttonCosActionPerformed

    private void buttonSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSecActionPerformed
        addTextToLabel("sec ");
    }//GEN-LAST:event_buttonSecActionPerformed

    private void buttonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTanActionPerformed
        addTextToLabel("tan ");
    }//GEN-LAST:event_buttonTanActionPerformed

    private void buttonInvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvertActionPerformed
        addTextToLabel("inv ");
    }//GEN-LAST:event_buttonInvertActionPerformed

    private void buttonFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFactorialActionPerformed
        addTextToLabel("!");
    }//GEN-LAST:event_buttonFactorialActionPerformed

    private void buttonStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStoreActionPerformed
        this.setMemory(Float.parseFloat(currentTextLabel.getText()));
        memoryLabel.setText("M");
    }//GEN-LAST:event_buttonStoreActionPerformed

    private void buttonMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryActionPerformed
        currentTextLabel.setText(String.valueOf(this.getMemory()));
        this.setMemory(0);
        memoryLabel.setText("No Mem");
    }//GEN-LAST:event_buttonMemoryActionPerformed

    private void buttonMemoryPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryPlusActionPerformed
        if(this.getMemory() == 0) return;
        
        this.setMemory(Float.parseFloat(currentTextLabel.getText()) + this.getMemory());
        memoryLabel.setText("M");
    }//GEN-LAST:event_buttonMemoryPlusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonDot;
    private javax.swing.JButton buttonFactorial;
    private javax.swing.JButton buttonInvert;
    private javax.swing.JButton buttonMemory;
    private javax.swing.JButton buttonMemoryPlus;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonPower;
    private javax.swing.JButton buttonResult;
    private javax.swing.JButton buttonRootOfN;
    private javax.swing.JButton buttonSec;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonSpace;
    private javax.swing.JButton buttonSquareRoot;
    private javax.swing.JButton buttonStore;
    private javax.swing.JButton buttonTan;
    private javax.swing.JTextField currentTextLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel memoryLabel;
    // End of variables declaration//GEN-END:variables
}
